name: "Netlify Previews"

on:
  pull_request:
    types: ["opened", "edited", "synchronize"]

permissions:
  contents: read
  statuses: write
  pull-requests: write

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Sets the branch name as environment variable
      - uses: nelonoel/branch-name@v1.0.1

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Netlify
        id: netlify_deploy
        uses: fntsrlike/action-netlify-deploy@v2
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          build_directory: dist # Ensure this matches your actual build directory
          deploy_alias: ${{ env.BRANCH_NAME }}
      - name: Status check
        uses: Sibz/github-status-action@v1.1.1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: Netlify preview
          state: success
          target_url: ${{ env.NETLIFY_PREVIEW_URL }}
