name: "Netlify Preview Deploy"

on:
  pull_request:
    types: ["opened", "edited", "synchronize"]

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest

    steps:
      - name: Build project
        run: npm run build
      - name: Navigate to project directory
        run: cd parser
      - uses: actions/checkout@v3
      - uses: fntsrlike/action-netlify-deploy@v2
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
