name: Test CI
on:
  push:
    branches: [main]
jobs:
  test:
    name: Something that updates labels
    runs-on: ubuntu-18.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      # Do something with labels
      # Then run this Action
      - name: Color all labels
        uses: AnandChowdhary/color-labels-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
