on:
  pull_request:
    types: [opened, review_requested]

jobs:
  telegram_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Event Type
        id: determine_event
        run: |
          if [ "${{ github.event.action }}" == "opened" ]; then
            echo "::set-output name=event_type::Pull Request Opened"
          elif [ "${{ github.event.action }}" == "review_requested" ]; then
            echo "::set-output name=event_type::Review Requested"
          fi

      - name: Generate Random Event Data
        id: generate_event_data
        if: steps.determine_event.outputs.event_type != null
        run: |
          # Generate some random event data
          echo "::set-output name=event_data::{\"event1\": \"${{ github.event.action }}", \"event2\": \"data2\"}"

      - name: Send Telegram Notification
        if: steps.determine_event.outputs.event_type != null
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🚨 ${{ steps.determine_event.outputs.event_type }} 🚨
            ${{ steps.generate_event_data.outputs.event_data }}
            Author: ${{ github.actor }}
            Title: ${{ github.event.pull_request.title }}
            Link: ${{ github.event.pull_request.html_url }}
