on:
  pull_request:
    types: [opened, review_requested]

jobs:
  telegram_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Event Type
        id: determine_event
        run: |
          if [ "${{ github.event.action }}" == "opened" ]; then
            echo "event_type=🚨Pull Request Opened🚨" >> $GITHUB_ENV
          elif [ "${{ github.event.action }}" == "review_requested" ]; then
            echo "event_type=Review Requested" >> $GITHUB_ENV
          fi

      - name: Determine Requested Reviewers
        id: determine_reviewers
        if: steps.determine_event.outputs.event_type == 'Review Requested'
        run: |
          # Check if requested reviewers exist and if it's an array
          if [ "${{ github.event.pull_request.requested_reviewers }}" != "null" ] && [ "$(echo "${{ github.event.pull_request.requested_reviewers }}" | jq 'type')" == "array" ]; then
            requested_reviewers=$(echo "${{ github.event.pull_request.requested_reviewers }}" | jq -r '.[].login' | paste -sd ", ")
            echo "requested_reviewers=$requested_reviewers" >> $GITHUB_ENV
          else
            echo "requested_reviewers=N/A" >> $GITHUB_ENV
          fi

      - name: Send Telegram Notification
        if: steps.determine_event.outputs.event_type != null
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ steps.determine_event.outputs.event_type }}
            Reviewers Requested: ${{ env.requested_reviewers }}
            ${{ github.event.pull_request.requested_reviewers }}
            Author: ${{ github.actor }}
            Title: ${{ github.event.pull_request.title }}
            Link: ${{ github.event.pull_request.html_url }}
