on:
  pull_request:
    types: [opened, reopened, review_requested]

jobs:
  telegram_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Event Type
        id: determine_event
        run: |
          if [ "${{ github.event_name }}" == "pull_request_review" ]; then
            echo "::set-output name=event_type::Pull Request Review"
          else
            echo "::set-output name=event_type::Pull Request"
          fi

      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🚨 ${{ github.event_name }} || ${{ steps.determine_event.outputs.event_type }} 🚨
