name: Telegram Notification

on:
  pull_request:
    types: [opened, reopened, review_requested]
  pull_request_review:
    types: [submitted]

jobs:
  telegram_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Set Notification Message
        id: set_notification_message
        run: |
          if [ "${{ github.event_name }}" == "pull_request_review" ]; then
            author="${{ github.actor }} request review"
            event="Pull Request Review"
          else
            author="${{ github.actor }}"
            event="Pull Request"
          fi

          message="🚨 $event Event 🚨
          Author: $author
          Title: ${{ github.event.pull_request.title }} 
          Link: ${{ github.event.pull_request.html_url }}"
          echo "::set-output name=message::$message"

      - name: Send Telegram Notification
        if: github.event_name == 'pull_request' || steps.check_review_requested.outputs.requested == 'true'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: ${{ steps.set_notification_message.outputs.message }}
