on:
  pull_request:
    types: [opened, review_requested]

jobs:
  telegram_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Event Type
        id: determine_event
        run: |
          if [ "${{ github.event.action }}" == "opened" ]; then
            echo "::set-output name=event_type::Pull Request Opened"
          elif [ "${{ github.event.action }}" == "review_requested" ]; then
            echo "::set-output name=event_type::Review Requested"
          fi

      - name: Determine Requested Reviewers
        id: determine_reviewers
        if: steps.determine_event.outputs.event_type == 'Review Requested'
        run: |
          requested_reviewers=$(echo "${{ github.event.pull_request.requested_reviewers }}" | jq -r '.[].login' | paste -sd ", ")
          echo "::set-output name=requested_reviewers::$requested_reviewers"

      - name: Send Telegram Notification
        if: steps.determine_event.outputs.event_type != null
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🚨 ${{ steps.determine_event.outputs.event_type }} 🚨
            Author: ${{ github.actor }}
            Reviewers Requested: ${{ steps.determine_reviewers.outputs.requested_reviewers }}
            Title: ${{ github.event.pull_request.title }}
            Link: ${{ github.event.pull_request.html_url }}
