on:
  pull_request:
    types: [opened, review_requested]

jobs:
  telegram_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Event Type
        id: determine_event
        run: |
          if [ "${{ github.event.action }}" == "opened" ]; then
            echo "::set-output name=event_type::Pull Request Opened"
          elif [ "${{ github.event.action }}" == "review_requested" ]; then
            echo "::set-output name=event_type::Review Requested"
          fi

      - name: Set Notification Message
        id: set_notification_message
        run: |
          echo "🚨 ${{ steps.determine_event.outputs.event_type }} 🚨" >> message.txt
          echo "Author: ${{ github.actor }}" >> message.txt
          echo "Title: ${{ github.event.pull_request.title }}" >> message.txt
          if [ "${{ steps.determine_event.outputs.event_type }}" == "Review Requested" ]; then
            echo "Requested Reviewers: ${{ join(github.event.pull_request.requested_reviewers.*.login, ', ') }}" >> message.txt
          fi
          echo "Link: ${{ github.event.pull_request.html_url }}" >> message.txt

      - name: Send Telegram Notification
        if: steps.determine_event.outputs.event_type != null
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            $(cat message.txt)
