on:
  pull_request:
    types: [opened, review_requested]

jobs:
  telegram_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Event Type
        id: determine_event
        run: |
          if [ "${{ github.event.action }}" == "opened" ]; then
            echo "::set-output name=event_type::Pull Request Opened"
          elif [ "${{ github.event.action }}" == "review_requested" ]; then
            echo "::set-output name=event_type::Review Requested"
          fi

      - name: Determine Requested Reviewers
        id: determine_reviewers
        if: steps.determine_event.outputs.event_type == 'Review Requested'
        run: |
          # Check if requested reviewers exist and if it's an array
          if [ "${{ github.event.pull_request.requested_reviewers }}" != "null" ] && [ "$(echo "${{ github.event.pull_request.requested_reviewers }}" | jq 'type')" == "array" ]; then
            requested_reviewers=$(echo "${{ github.event.pull_request.requested_reviewers }}" | jq -r '.[].login' | paste -sd ", ")
            echo "::set-output name=requested_reviewers::$requested_reviewers"
          else
            echo "::set-output name=requested_reviewers::N/A"
          fi

      - name: Generate Random Event Data
        id: generate_event_data
        if: steps.determine_event.outputs.event_type != null
        run: |
          # Generate some random event data
          echo "::set-output name=event_data::{\"event1\": \"data1\", \"event2\": \"data2\"}"

      - name: Send Telegram Notification
        if: steps.determine_event.outputs.event_type != null
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🚨 ${{ steps.determine_event.outputs.event_type }} 🚨
            Reviewers Requested: ${{ steps.determine_reviewers.outputs.requested_reviewers }}
            Author: ${{ github.actor }}
            Title: ${{ github.event.pull_request.title }}
            Link: ${{ github.event.pull_request.html_url }}
