name: Telegram Notification

on:
  pull_request:
    types: [opened, reopened, review_requested]
  pull_request_review:
    types: [submitted]
jobs:
  telegram_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Review Requested
        id: check_review_requested
        if: github.event_name == 'pull_request_review' && github.event.action == 'submitted'
        run: |
          if [ "${{ github.event.review.state }}" == "requested" ]; then
            echo "::set-output name=requested::true"
            echo "::set-output name=requested_reviewers::${{ join(github.event.pull_request.requested_reviewers.*.login, ', ') }}"
          else
            echo "::set-output name=requested::false"
          fi

      - name: Set Notification Message
        id: set_notification_message
        if: github.event_name == 'pull_request_review'
        run: |
          event="Pull Request Review"
          author="${{ github.actor }} request review"
          requested_reviewers="${{ steps.check_review_requested.outputs.requested_reviewers }}"
          special_message=""
          if [ "${{ steps.check_reviews.outputs.all_approved }}" == "true" ]; then
            special_message="🎉 All reviews approved for this pull request! 🎉"
          fi

          message="🚨 $event Event 🚨\nAuthor: $author\n$([[ ! -z $requested_reviewers ]] && echo 'Requested Reviewers: '$requested_reviewers)\nTitle: ${{ github.event.pull_request.title }}\nLink: ${{ github.event.pull_request.html_url }}"
        echo "::set-output name=message::$message"
      - name: Set Notification Message
        id: set_notification_message_pr
        if: github.event_name == 'pull_request'
        run: |
          event="Pull Request"
          author="${{ github.actor }}"
          requested_reviewers=""
          special_message=""
          if [ "${{ steps.check_reviews.outputs.all_approved }}" == "true" ]; then
            special_message="🎉 All reviews approved for this pull request! 🎉"
          fi
          message="🚨 $event Event 🚨\nAuthor: $author\n$([[ ! -z $requested_reviewers ]] && echo 'Requested Reviewers: '$requested_reviewers)\nTitle: ${{ github.event.pull_request.title }}\nLink: ${{ github.event.pull_request.html_url }}\n$special_message"